name: docs build
on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - main
  repository_dispatch:
    branches:
      - main
  watch:
    branches:
      - main    

jobs:
  notion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: false
    - uses: mohuishou/notion-blog-actions@main
      with:
        notion_secret: ${{ secrets.NOTION_TOKEN }}
        database_id: ${{ secrets.NOTION_DATABASE_ID }}
        output: "./docs/"
        access_key_id: "${{ secrets.ALI_ID }}"
        access_key_secret: "${{ secrets.ALI_SECRET }}"
        bucket: "xxx"
        area: "${{ inputs.oss_endpoint }}"
        prefix: "image/"

    - name: git setting
      run: |
        git config --global user.email "hehouhui@foxmail.com"
        git config --global user.name "hehouhui"

    - name: update blog
      run: |
        git add docs
        git commit -m "feat: auto update by notion sync"
        git push
  LearnData-build:
    runs-on: ubuntu-latest
    needs: notion
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          # 获取所有标记和分支的所有历史记录（updatetime 必须，否则每次都会变化）
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      # 将读书笔记复制到静态页路径，然后构建页面
      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm cpx "docs/reading/**" docs/.vuepress/public/reading
          pnpm run docs:build
          > docs/.vuepress/dist/.nojekyll

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: docs/.vuepress/dist

      ### 没有服务器的话，请删除本区块代码，防止报错 ###
      # 将页面推送到服务器，timeout 时间从默认的 1 分钟调整到 10 分钟。
      #- name: 📂 Sync files
      #  uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #  with:
      #    local-dir: docs/.vuepress/dist/
      #    server: ${{ secrets.ftp_host }}
      #    username: ${{ secrets.ftp_username }}
      #    password: ${{ secrets.ftp_password }}
      #    port: ${{ secrets.ftp_port }} # 建议更改默认的 21 端口
      #    timeout: 600000
      ### 没有服务器的话，请删除本区块代码，防止报错 ###
