name: 自动同步notion

on:
  repository_dispatch:
    types:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: 開始運行
        uses: actions/checkout@v1

      - name: 安装node环境
        uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: 安装依赖
        run: |
          export TZ='Asia/Shanghai'
          npm install --prod
          
      - name: 拉取语雀/Notion的文章
        env:
          # Notion相关环境变量
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          # 图床相关环境变量，以github为例
          GITHUB_USER: ${{ secrets.IMG_GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.IMG_GITHUB_TOKEN }}
          GITHUB_REPO: ${{ secrets.IMG_GITHUB_REPO }}
        run: |
          # 对应package.json中的script.sync
          npm run sync      
      - name: 部署博客
        run: 
          cd ./source
          git init
          git config user.name "${{secrets.GIT_NAME}}"
          git config user.email "${{secrets.GIT_EMAIL}}"
          git add .
          git commit -m "Update"
          git push --force --quiet "https://${{secrets.GH_TOKEN}}@${{secrets.GH_REF}}" master:master
